spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HRMS
#    username: username
#    password: password
    username: root
    password: 190104a@
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
mybatis:
    type-aliases-package: com.example.hrms.biz.booking.model,
        com.example.hrms.biz.department.model,
        com.example.hrms.biz.meetingroom.model,
        com.example.hrms.biz.request.model,
        com.example.hrms.biz.role.model,
        com.example.hrms.biz.user.model
